### ISSUE TITLE
Zone parse fails if RRSIG does not have host label

### ISSUE THREAD

**Issue by petskratt** [Badcow/DNS#60] opened 2019-12-29 18:31 UTC
Parsing of zonefile fails with "Fatal error: Uncaught InvalidArgumentException:" if RRSIG record does not have host label. Following seems to be valid zone for `named-checkzone`:

```
poose.eu.		3600	IN SOA	ns.zone.eu. hostmaster.zone.eu. (
					2019122947 ; serial
					10800      ; refresh (3 hours)
					3600       ; retry (1 hour)
					2419200    ; expire (4 weeks)
					3600       ; minimum (1 hour)
					)
			3600	RRSIG	SOA 14 2 3600 (
					20200112073532 20191229133101 55179 poose.eu.
					utZQyR9wDynN8JE8DCVwYxix9eXpx45c4kDR
					ZqwzZnNVbz8UQv8Mt/AAqyqiKq4kHvGeczSp
					jj2fR8UIra3/eEowfeJzzPPuKmUsYO0WLuFy
					Ef8PJut23NefeEWo+1F7 )
			3600	NS	ns.zone.eu.
			3600	NS	ns2.zone.ee.
			3600	NS	ns3.zonedata.net.
			3600	RRSIG	NS 14 2 3600 (
					20200112073532 20191229133101 55179 poose.eu.
					bpGJmk6mA55QvkYejr33387hvWkg9z4pyhw4
					OLcw4NxTSVe8yna81Ey6jpbkkTTJxPBjo5fI
					kVNX3+12qG4fw4kswDzmzRvlTqXmujoLMbxx
					aAGW2YMATNJXM1d7PG77 )
			3600	A	217.146.69.44
			3600	RRSIG	A 14 2 3600 (
					20200112073532 20191229133101 55179 poose.eu.
					bDts/7a5qbal6s3ZYzS5puPSjEfys5yI6R/k
					prBBRDEfVcT6YwPaDT3VkVjKXdvpKX2/Dwpi
					jNAWkjpfsewCLmeImx3RgkzfuxfipRKtBUgu
					iPTBhkj/ft2halJziVXl )
```

RRSIG records appear to be interpreted as SOA, NS, A records when parsed as `Badcow\DNS\Parser\Parser::parse( "poose.eu.", $zonefile )`

Providing them with host label (or @) produces expected result.

And thanks for excellent library!

**Comment by samuelwilliams** [comment] 2019-12-30 11:16
Hi @petskratt 

Thanks for raising this issue.

I have found the root of the issue and have made a fix with tests on [a new branch](https://github.com/Badcow/DNS/tree/Issue60).

When determining if something is a resource name or some other element, it does a look ahead and sees what the next word is. In RRSIG's case, the next word is `A` so the parser thought that the resource name is `RRSIG`. This was simple enough to fix once the root cause was found.

Checkout [branch Issue60](https://github.com/Badcow/DNS/tree/Issue60) and make sure that it is working for you.

Thank you very much for raising this issue!

**Comment by petskratt** [comment] 2019-12-30 11:36
Now it parses correctly, thanks!

Just one remark - AlignedBuilder::build( $zone ) groups A, CNAME etc nicely together, but NSEC3 & RRSIG are in order found in source zone file with comments inserted whenever type changes (and it does change repeatedly). Result is valid, but could look better.

Source: [poose.eu.zone.txt](https://github.com/Badcow/DNS/files/4009670/poose.eu.zone.txt)

Output:
![Screenshot 2019-12-30 at 13 34 18](https://user-images.githubusercontent.com/712310/71580389-22658500-2b09-11ea-8621-abc88bf98123.png)

**Comment by samuelwilliams** [comment] 2019-12-30 21:25
Awesome!

I have pushed the second point you raised into Issue #61 

I will merge the branch into master and produce a bugfix release shortly.

Thanks for the issue!

**Comment by samuelwilliams** [comment] 2019-12-31 00:02
Merged.

**Closed by samuelwilliams** 2019-12-31 00:02 UTC
Labels: bug
